Repository true-myth/true-myth, pull requests merged in 2022-09, with the labels that each got.

#434 Update readme with v6.x requirements
  README.md
Labels: documentation

#436 chore: remove defunct parts of package
  .ember-cli
  package.json
Labels: internal

#437 docs: include doc comments in published types
  ts/publish.tsconfig.json
Labels: bug, documentation

#438 Add explicit support for TS 4.8
  .github/workflows/CI.yml
  README.md
  package.json
  yarn.lock
Labels: enhancement
