Repository true-myth/true-myth, pull requests merged in 2022-03, with the labels that each got.

#299 feat(maybe/find): type narrowing via predicates
  src/maybe.ts
  test/maybe.test.ts
Labels: enhancement

#315 Bump to TS v4.6 and add it to CI matrix
  .github/workflows/CI.yml
  README.md
  package.json
  yarn.lock
Labels: dependencies

#317 Forward-port CI, docs updates
  .github/workflows/CI.yml
  README.md
  package.json
  yarn.lock
Labels: dependencies, documentation
